### PR TITLE
Remove unnecessary else statements

### PR DESCRIPTION
**Pull request by sophuric**
Hi, I removed unnecessary `else` statements since `return`ing would automatically break out.

### CODE REVIEW

**Comment by DangoSky** [comment]
Yeah, you're right. But I think the effect of  ``else  return "white"`` and ``return "white"`` is  same, it'

**Comment by DangoSky** [comment]
Yeah, you're right. But I think the effect of both is same, it isn't necessary to modify it. @wooden-utensil

**Comment by sophuric** [comment]
@DangoSky I think you're right. It's still readable without `else`, but it's more obvious what it's doing with `else`. Thanks.

**Comment by DangoSky** [comment]
Excuse me, I am curious how you found this repository, are you also developing a 2048 game? @wooden-utensil

**Comment by sophuric** [comment]
@DangoSky I was looking for 2048 games (clones) and I found this one as the first one, I was going to fork it, so I could add a initial value selector so I could choose to start with 2048 tiles instead of 2 for example. And I did.

**Pull request closed without merging**
